cpp-sdl2: sdl::Texture Class Reference
sdl::Texture Class Reference
Class that represet a renderer texture.
#include <texture.hpp>
Classes
class Lock
Lock object that permit to access pixels directly on texture.
Public Member Functions
Texture (SDL_Texture *t)
Construct texture from C SDL_Texture object.
SDL_Texture * ptr () const
Get SDL_Texture pointer from texture.
Texture (SDL_Renderer *render, Uint32 format, SDL_TextureAccess access, int w, int h)
Create texture.
Texture ()=default
Default constructor for empty texture object.
Texture (SDL_Renderer *render, Uint32 format, SDL_TextureAccess access, Vec2i size)
Create texture.
Texture (SDL_Renderer *render, Surface const &surface)
Create texture from surface.
Texture (SDL_Renderer *render, std::string const &filename)
Create texture from file.
Texture (Texture &&other) noexcept
Move texture into this one.
Texture & operator= (Texture &&other) noexcept
move texture into this one
Texture (Texture const &)=delete
Non copiable.
Texture & operator= (Texture const &)=delete
Non copiable.
~Texture ()
Destroy texture when it's not in use anymore.
void set_blendmode (SDL_BlendMode const &bm) const
Set texture blend mode.
SDL_BlendMode blendmode () const
Get texture blend mode.
void set_colormod (Color const &color) const
Set colormod.
void set_colormod (Uint8 r, Uint8 g, Uint8 b) const
Set colormod.
Color colormod () const
Get colormod.
void set_alphamod (Uint8 alpha) const
Set alphamod.
Uint8 alphamod () const
Set alphamod.
void set_coloralphamod (Uint8 r, Uint8 g, Uint8 b, Uint8 a) const
Set coloralphamod.
void set_coloralphamod (Color const &c) const
Set coloralphamod.
Color coloralphamod () const
Get coloralphamod.
Uint32 format () const
Get texture format.
int access () const
Access texture.
Vec2i size () const
Get texture size.
Lock lock ()
lock texture for direct access to content
Lock lock (Rect const &rect)
lock texture rect
Private Attributes
SDL_Texture * texture_ = nullptr
Detailed Description
Class that represet a renderer texture.
Definition at line 17 of file texture.hpp.
Constructor & Destructor Documentation
sdl::Texture::Texture (SDL_Texture * t) inline explicit
Construct texture from C SDL_Texture object.
Definition at line 73 of file texture.hpp.
sdl::Texture::Texture (SDL_Renderer * render, Uint32 format, SDL_TextureAccess access, int w, int h) inline
Create texture.
Definition at line 79 of file texture.hpp.
sdl::Texture::Texture () default
Default constructor for empty texture object.
sdl::Texture::Texture (SDL_Renderer * render, Uint32 format, SDL_TextureAccess access, Vec2i size) inline
Create texture.
Definition at line 94 of file texture.hpp.
References access(), and format().
sdl::Texture::Texture (SDL_Renderer * render, Surface const & surface) inline
Create texture from surface.
Definition at line 104 of file texture.hpp.
References sdl::Surface::ptr(), and sdl::Texture::Lock::texture_.
sdl::Texture::Texture (SDL_Renderer * render, std::string const & filename) inline
Create texture from file.
Definition at line 111 of file texture.hpp.
sdl::Texture::Texture (Texture && other) inline noexcept
Move texture into this one.
Definition at line 117 of file texture.hpp.
sdl::Texture::Texture (Texture const &) delete
Non copiable.
sdl::Texture::~Texture () inline
Destroy texture when it's not in use anymore.
Definition at line 138 of file texture.hpp.
References sdl::Texture::Lock::texture_.
Member Function Documentation
int sdl::Texture::access () const inline
Access texture.
Definition at line 221 of file texture.hpp.
References sdl::Texture::Lock::texture_.
Referenced by Texture().
Uint8 sdl::Texture::alphamod () const inline
Set alphamod.
Definition at line 183 of file texture.hpp.
References sdl::Texture::Lock::texture_.
Referenced by coloralphamod().
SDL_BlendMode sdl::Texture::blendmode () const inline
Get texture blend mode.
Definition at line 147 of file texture.hpp.
References sdl::Texture::Lock::texture_.
Color sdl::Texture::coloralphamod () const inline
Get coloralphamod.
Definition at line 204 of file texture.hpp.
References alphamod(), and colormod().
Color sdl::Texture::colormod () const inline
Get colormod.
Definition at line 168 of file texture.hpp.
References sdl::Texture::Lock::texture_.
Referenced by coloralphamod().
Uint32 sdl::Texture::format () const inline
Get texture format.
Definition at line 212 of file texture.hpp.
References sdl::Texture::Lock::texture_.
Referenced by Texture().
Lock sdl::Texture::lock () inline
lock texture for direct access to content
Definition at line 239 of file texture.hpp.
References sdl::Texture::Lock::texture_.
Lock sdl::Texture::lock (Rect const & rect) inline
lock texture rect
Definition at line 242 of file texture.hpp.
References sdl::Texture::Lock::texture_.
Texture& sdl::Texture::operator= (Texture && other) inline noexcept
move texture into this one
Definition at line 121 of file texture.hpp.
References sdl::Texture::Lock::texture_.
Texture& sdl::Texture::operator= (Texture const &) delete
Non copiable.
SDL_Texture* sdl::Texture::ptr () const inline
Get SDL_Texture pointer from texture.
Definition at line 76 of file texture.hpp.
References sdl::Texture::Lock::texture_.
void sdl::Texture::set_alphamod (Uint8 alpha) const inline
Set alphamod.
Definition at line 177 of file texture.hpp.
References sdl::Texture::Lock::texture_.
Referenced by set_coloralphamod().
void sdl::Texture::set_blendmode (SDL_BlendMode const & bm) const inline
Set texture blend mode.
Definition at line 141 of file texture.hpp.
References sdl::Texture::Lock::texture_.
void sdl::Texture::set_coloralphamod (Uint8 r, Uint8 g, Uint8 b, Uint8 a) const inline
Set coloralphamod.
Definition at line 192 of file texture.hpp.
References set_alphamod(), and set_colormod().
void sdl::Texture::set_coloralphamod (Color const & c) const inline
Set coloralphamod.
Definition at line 198 of file texture.hpp.
References set_alphamod(), and set_colormod().
void sdl::Texture::set_colormod (Color const & color) const inline
Set colormod.
Definition at line 156 of file texture.hpp.
Referenced by set_coloralphamod().
void sdl::Texture::set_colormod (Uint8 r, Uint8 g, Uint8 b) const inline
Set colormod.
Definition at line 161 of file texture.hpp.
References sdl::Texture::Lock::texture_.
Vec2i sdl::Texture::size () const inline
Get texture size.
Definition at line 230 of file texture.hpp.
References sdl::Texture::Lock::texture_.
Member Data Documentation
SDL_Texture* sdl::Texture::texture_ = nullptr private
Definition at line 245 of file texture.hpp.
The documentation for this class was generated from the following file:
/home/travis/build/Edhebi/cpp-sdl2/sources/cpp-sdl2/texture.hpp