cpp-sdl2: sdl::Surface::Lock Class Reference
sdl::Surface::Lock Class Reference
Represent a lock to safely access surface content.
#include <surface.hpp>
Public Member Functions
Pixel at (Vec2i const &pos) const
Get pixel at given coordinates inside surface.
Pixel at (size_t x, size_t y) const
Get pixel at specified location inside surface.
Pixel operator[] (Vec2i const &pos) const
Get pixel at specified location via operator[].
void * raw_array () const
Get access to the raw array of pixels.
~Lock ()
Free the lock.
Private Member Functions
constexpr Lock (SDL_Surface &surface_)
Private constructor for lock object.
Private Attributes
SDL_Surface * surface_
Raw pointer to the surface.
Friends
class Surface
Detailed Description
Represent a lock to safely access surface content.
Definition at line 25 of file surface.hpp.
Constructor & Destructor Documentation
sdl::Surface::Lock::~Lock () inline
Free the lock.
Definition at line 48 of file surface.hpp.
References surface_.
constexpr sdl::Surface::Lock::Lock (SDL_Surface & surface_) inline private
Private constructor for lock object.
Definition at line 52 of file surface.hpp.
Member Function Documentation
Pixel sdl::Surface::Lock::at (Vec2i const & pos) const inline
Get pixel at given coordinates inside surface.
Definition at line 31 of file surface.hpp.
References at().
Referenced by at(), and operator[]().
Pixel sdl::Surface::Lock::at (size_t x, size_t y) const inline
Get pixel at specified location inside surface.
Definition at line 33 of file surface.hpp.
References surface_.
Pixel sdl::Surface::Lock::operator[] (Vec2i const & pos) const inline
Get pixel at specified location via operator[].
Definition at line 42 of file surface.hpp.
References at().
void* sdl::Surface::Lock::raw_array () const inline
Get access to the raw array of pixels.
Definition at line 45 of file surface.hpp.
References surface_.
Friends And Related Function Documentation
friend class Surface friend
Definition at line 27 of file surface.hpp.
Member Data Documentation
SDL_Surface* sdl::Surface::Lock::surface_ private
Raw pointer to the surface.
Definition at line 55 of file surface.hpp.
Referenced by at(), raw_array(), and ~Lock().
The documentation for this class was generated from the following file:
/home/travis/build/Edhebi/cpp-sdl2/sources/cpp-sdl2/surface.hpp