cpp-sdl2: sdl::Event::EventFilter Struct Reference
sdl::Event::EventFilter Struct Reference
Event filter object.
#include <event.hpp>
Public Types
using func_type = bool(*)(void *, Event &)
Public Member Functions
EventFilter (func_type filter, void *userdata)
EventFilter (func_type filter)
~EventFilter ()
void filter_queue ()
void set ()
void add_watcher ()
void del_watcher ()
Static Public Member Functions
static int call_filter (void *data, SDL_Event *event)
static void unset ()
Public Attributes
void * userdata_ = nullptr
func_type filter_ = nullptr
bool isWatcher_ = false
Detailed Description
Event filter object.
Definition at line 323 of file event.hpp.
Member Typedef Documentation
using sdl::Event::EventFilter::func_type = bool (*)(void*, Event&)
Definition at line 325 of file event.hpp.
Constructor & Destructor Documentation
sdl::Event::EventFilter::EventFilter (func_type filter, void * userdata) inline
Definition at line 331 of file event.hpp.
sdl::Event::EventFilter::EventFilter (func_type filter) inline
Definition at line 336 of file event.hpp.
sdl::Event::EventFilter::~EventFilter () inline
Definition at line 338 of file event.hpp.
References del_watcher(), and isWatcher_.
Member Function Documentation
void sdl::Event::EventFilter::add_watcher () inline
Definition at line 356 of file event.hpp.
References call_filter(), and isWatcher_.
static int sdl::Event::EventFilter::call_filter (void * data, SDL_Event * event) inline static
Definition at line 343 of file event.hpp.
References filter_, and sdl::Event::ref_from().
Referenced by add_watcher(), del_watcher(), filter_queue(), and set().
void sdl::Event::EventFilter::del_watcher () inline
Definition at line 362 of file event.hpp.
References call_filter(), and isWatcher_.
Referenced by ~EventFilter().
void sdl::Event::EventFilter::filter_queue () inline
Definition at line 350 of file event.hpp.
References call_filter().
void sdl::Event::EventFilter::set () inline
Definition at line 352 of file event.hpp.
References call_filter(), and userdata_.
static void sdl::Event::EventFilter::unset () inline static
Definition at line 354 of file event.hpp.
Member Data Documentation
func_type sdl::Event::EventFilter::filter_ = nullptr
Definition at line 328 of file event.hpp.
Referenced by call_filter().
bool sdl::Event::EventFilter::isWatcher_ = false
Definition at line 329 of file event.hpp.
Referenced by add_watcher(), del_watcher(), and ~EventFilter().
void* sdl::Event::EventFilter::userdata_ = nullptr
Definition at line 327 of file event.hpp.
Referenced by set().
The documentation for this struct was generated from the following file:
/home/travis/build/Edhebi/cpp-sdl2/sources/cpp-sdl2/event.hpp